rootURL: https://iineva.github.io/helm-chart/mirror
source:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
  charts:
    - kubernetes-dashboard
    - traefik
    - docker-registry
    - rocketchat
    - grafana
    - prometheus
- name: gomods
  url: https://athens.blob.core.windows.net/charts
- name: gitlab
  url: https://charts.gitlab.io
  charts:
    - gitlab
    - gitlab-runner
- name: jetstack
  url: https://charts.jetstack.io
  charts:
    - cert-manager
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
  charts:
    - ingress-nginx
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  charts:
    - raw
- name: bitnami
  url: https://charts.bitnami.com
- name: harbor
  url: https://helm.goharbor.io
  charts:
    - harbor
- name: elastic
  url: https://helm.elastic.co
  charts:
    - elasticsearch
    - filebeat
    - logstash
    - kibana
