# your public root url.
rootURL: https://iineva.github.io/helm-chart/mirror
# set 0 to sync all chart versions.
majorVersions: 2
# if true create index.yaml only. and ensure all resource path is A full URL.
downloadFiles: true
downloadConcurrent: 20
source:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
    # charts to filter, if empty will sync all charts.
    charts:
      - kubernetes-dashboard
      - traefik
      - docker-registry
      - rocketchat
      - grafana
      - prometheus
  - name: gitlab
    url: https://charts.gitlab.io
    charts:
      - gitlab
      - gitlab-runner
  - name: jetstack
    url: https://charts.jetstack.io
    charts:
      - cert-manager
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
    charts:
      - ingress-nginx
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com
    charts:
      - raw
  - name: harbor
    url: https://helm.goharbor.io
    charts:
      - harbor
  - name: elastic
    url: https://helm.elastic.co
    charts:
      - elasticsearch
      - filebeat
      - logstash
      - kibana
  - name: loki
    url: https://grafana.github.io/loki/charts
    charts:
      - loki
      - loki-stack
      - promtail
