# Default values for externalServices.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

enabled: false


# mysql:
#   fullName: internal-mysql
#   enabled: true
#   ip: 192.168.9.227
#   port: 3306
#   protocol: TCP
# mongo:
#   enabled: true
#   ip: 192.168.9.227
#   port: 27017
#   protocol: TCP
# redis:
#   enabled: false
#   ip: 192.168.9.227
#   port: 6379
#   targetPort: 9720