apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "v2ray.fullname" . }}
  labels:
    {{- include "v2ray.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "v2ray.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "v2ray.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "v2ray.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "v2ray.fullname" . }}
    {{- if .Values.nodeName }}
      nodeName: {{ .Values.nodeName }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if not .Values.clientMode }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: {{ .Values.service.protocol }}
            {{- range .Values.nodePorts }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ default "TCP" .protocol }}
            {{- end }}
          {{- if eq .Values.service.protocol "TCP" }}
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          {{- end }}
{{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/v2ray/config.json
              subPath: config.json
              readOnly: true
          {{- if .Values.timezone }}
          env:
            - name: TZ
              value: {{ .Values.timezone }}
          {{- end }}
        - name: {{ .Chart.Name }}-trojan
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.trojan.image.repository }}:{{ .Values.trojan.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.timezone }}
          env:
            - name: TZ
              value: {{ .Values.timezone }}
          {{- end }}
          command:
          - trojan-go
          - -client
          - -remote
          - {{ .Values.trojan.client.host }}:{{ .Values.trojan.client.port }}
          - -local
          - 127.0.0.1:{{ .Values.trojan.client.localPort }}
          - -password
          - {{ .Values.trojan.client.password }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
