apiVersion: v1
kind: Service
metadata:
  name: {{ include "v2ray.fullname" . }}
  labels:
    {{- include "v2ray.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: {{ .Values.service.protocol }}
{{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.port }}
{{- end }}
      name: http
{{- if eq .Values.service.type "NodePort" }}
#  externalTrafficPolicy: Local
{{- end }}
  selector:
    {{- include "v2ray.selectorLabels" . | nindent 4 }}
