{{- if not .Values.clientMode }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "v2ray.fullname" . }}
  labels:
    {{- include "v2ray.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "v2ray.selectorLabels" . | nindent 4 }}

{{- if .Values.nodePorts }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "v2ray.fullname" . }}-node-port
  labels:
    {{- include "v2ray.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    {{- range .Values.nodePorts }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ default "TCP" .protocol }}
      nodePort: {{ .port }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "v2ray.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}