apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "ipa-server.fullname" . }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClassName }}
