{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ipa-server.serviceAccountName" . }}
  labels:
{{ include "ipa-server.labels" . | nindent 4 }}
{{- end -}}
