apiVersion: v1
kind: Service
metadata:
  name: {{ include "traefik.fullname" . }}
  namespace: {{ template "traefik.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "traefik.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 80
      name: http
    - protocol: TCP
      port: 443
      nodePort: 443
      name: https
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: {{ include "traefik.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
