apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "traefik.serviceAccountName" . }}
  namespace: {{ template "traefik.name" . }}
  labels:
    {{- include "traefik.labels" . | nindent 4 }}