{{- range .Values.submodules }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-server.name" $ }}-{{ .name }}
spec:
  replicas: {{ default $.Values.default.replicas .replicas }}
  selector:
    matchLabels:
      app: {{ include "api-server.name" $ }}-{{ .name }}
  template:
    metadata:
      labels:
        app: {{ include "api-server.name" $ }}-{{ .name }}
      annotations:
        checksum/config: {{ include "api-server.configHash" (dict "root" $ "name" .configMapName) | quote }}
        {{- if not (default $.Values.default.annotations .annotations | empty) }}
        {{- default $.Values.default.annotations .annotations | toYaml | nindent 8 }}
        {{- end }}
    spec:
    {{- with $.Values.default.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .name }}
          image: "{{ default $.Values.default.repository .repository }}/{{ .name }}:{{ default $.Values.default.tag .tag }}"
          ports:
            - name: http
              containerPort: {{ default 80 .containerPort }}
          imagePullPolicy: IfNotPresent
          {{- if not (default false .disableHealthCheck) }}
          livenessProbe:
            httpGet:
              path:  {{ default "/healthz" .healthCheckPath }}
              port: http
            initialDelaySeconds: {{ default 10 .initialDelaySeconds }}
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: {{ default "/healthz" .healthCheckPath }}
              port: http
            initialDelaySeconds: {{ default 10 .initialDelaySeconds }}
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          {{- end }}
          resources:
            {{ default "{}" $.Values.default.resources .resources }}
          {{- if (index . "configMapName") }}
          envFrom:
            - configMapRef:
                name: {{ include "api-server.name" $ }}-{{ .configMapName }}
          {{- end }}
          {{- if (index . "env") }}
          env:
            {{- range $key, $value := .env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
{{- end }}