{{- range $subIndex, $submodules := .Values.submodules }}
{{ if $submodules.ingress }}
{{- range $index, $ingress := $submodules.ingress }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "api-server.name" $ }}-{{ $submodules.name }}-{{ default $index $ingress.name }}
  annotations:
    {{- with $.Values.default.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $ingress.anitations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if $ingress.addPrefix }}
    nginx.ingress.kubernetes.io/rewrite-target: {{ $ingress.addPrefix }}$request_uri
    {{- end }}
spec:
  rules:
    - host: {{ default $.Values.host $ingress.host }}
      http:
        paths:
          {{- range (splitList "," $ingress.path) }}
          - path: {{ . }}
            backend:
              serviceName: {{ include "api-server.name" $ }}-{{ $submodules.name }}
              servicePort: http
          {{- end }}
  tls:
  {{- if $ingress.TLS }}
    {{- toYaml . | nindent 4 }}
  {{- else }}
  {{- range $.Values.TLSHosts }}
  - hosts:
      - {{ .host | quote }}
    secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
