{{- range .Values.submodules }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "api-server.name" $ }}-{{ .name }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "api-server.name" $ }}-{{ .name }}
  ports:
    - name: http
      port: 80
      targetPort: http
{{- end}}