{{- $length := len .Values.configFiles }} {{- if gt $length  0 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generalServer.fullname" . }}
  labels:
    app: {{ include "generalServer.name" . }}
    chart: {{ include "generalServer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.configFiles }}
  {{ $key }}: |-
{{ $value | default "" | indent 4 }}
{{- end -}}
{{- end }}