apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-web.fullname" . }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
  kube.config: |
    {{- toYaml .Values.kubectlConfig | nindent 4 }}
