apiVersion: v1
kind: Secret
metadata:
  name: weave-secret
  namespace: weave
data:
  # 生成账号的方法，一行一个账号
  # htpasswd -nb admin steven
  users: |
  {{- if .Values.users }}
    {{- join "\n" .Values.users | b64enc | nindent 4 }}
  {{- else }}
    YWRtaW46JGFwcjEkVWE1R2J4b1IkSUhrcFpENmxBRlhKZHJ2M3JHeTdmMAoK
  {{- end }}