apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "activemq.fullname" . }}
data:
  jetty-realm.properties: |

    {{- if .Values.password }}
    admin: {{ .Values.password }}, admin
    {{- end }}
