apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nps-server.fullname" . }}
data:
  nps.conf: |
    appname=nps
    #Boot mode(dev|pro)
    runmode=pro

    #HTTP(S) proxy port, no startup if empty
    http_proxy_ip=0.0.0.0
    http_proxy_port=80
    # https_proxy_port=443
    https_just_proxy=false
    #default https certificate setting
    # https_default_cert_file=conf/server.pem
    # https_default_key_file=conf/server.key

    ##bridge
    bridge_type=tcp
    bridge_port=80
    bridge_ip=0.0.0.0

    # Public password, which clients can use to connect to the server
    # After the connection, the server will be able to open relevant ports and parse related domain names according to its own configuration file.
    {{- if .Values.publicVKey}}
    public_vkey={{ .Values.publicVKey }}
    {{- end }}

    #Traffic data persistence interval(minute)
    #Ignorance means no persistence
    #flow_store_interval=1

    # log level LevelEmergency->0  LevelAlert->1 LevelCritical->2 LevelError->3 LevelWarning->4 LevelNotice->5 LevelInformational->6 LevelDebug->7
    log_level=7
    log_path=nps.log

    #Whether to restrict IP access, true or false or ignore
    #ip_limit=true

    #p2p
    #p2p_ip=127.0.0.1
    #p2p_port=6000

    #web
    web_host={{ .Values.web.host }}
    web_username={{ .Values.web.user }}
    web_password={{ .Values.web.pass }}
    web_port=80
    web_ip=0.0.0.0

    #Web API unauthenticated IP address(the len of auth_crypt_key must be 16)
    auth_key=S7ZJQCOQSPV10DJD
    auth_crypt_key=ENB5E09Z9NV7VJ9E

    #allow_ports=9001-9009,10001,11000-12000

    #Web management multi-user login
    allow_user_login=false
    allow_user_register=false
    allow_user_change_username=false


    #extension
    allow_flow_limit=false
    allow_rate_limit=false
    allow_tunnel_num_limit=false
    allow_local_proxy=true
    allow_connection_num_limit=false
    allow_multi_ip=false
    system_info_display=true

    #cache
    http_cache=false
    http_cache_length=100


