apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nps-server.fullname" . }}
  labels:
    {{- include "nps-server.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nps-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nps-server.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "nps-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "nps-server.fullname" . }}
        - name: config
          configMap:
            name: {{ include "nps-server.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: proxy
              containerPort: 8024
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /login/index
              port: http
              httpHeaders:
                - name: Host
                  value: {{ .Values.web.host }}
          readinessProbe:
            httpGet:
              path: /login/index
              port: http
              httpHeaders:
                - name: Host
                  value: {{ .Values.web.host }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /nps/conf/nps.conf
              subPath: nps.conf
              readOnly: true
            - name: data
              mountPath: /nps/conf/
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
