default:
  repository: example.local
  imagePullSecrets:
  annotations: {}
  resources: {}
  replicas: 2
  ingress: {}
  tag: "latest"

host: example.local
namespace: api-server

TLS: []

submodules:
  - name: api
    # 关闭健康检测
    disableHealthCheck: false
    # 健康检测路径
    healthCheckPath: /healthz
    # 健康启动检测延迟
    initialDelaySeconds: 10
    containerPort: 80
    ingress:
        # 名字可选，出现在ingress名字后缀，默认用index做后缀
      - name: api
        # 捕获路径
        path: /
        # annotations
        annotations: {}

env:
  TZ: Asia/Shanghai
  PORT: "8000"
  APP_ENV: "prod"
  GIN_MODE: "release"
