apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "verdaccio.fullname" . }}
  labels:
    {{- include "verdaccio.selectorLabels" . | nindent 4 }}
data:
  config.yaml: |-
{{ toYaml .Values.configMap | indent 4 }}