apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gitlab.fullname" . }}
data:
    # 确保log时区正确显示
    TZ: Asia/Shanghai
    HOSTNAME: {{ .Values.host }}
    # 配置Gitlab
    GITLAB_OMNIBUS_CONFIG_X: |
        # 备份保持时间（7天）
        gitlab_rails['backup_keep_time'] = 604800
        #postgresql['shared_buffers'] = '256MB'
        external_url '{{ .Values.external_url }}'
        gitlab_rails['gitlab_shell_ssh_port'] = 9000
        # 头像始终使用https
        gitlab_rails['gravatar_plain_url'] = "https://secure.gravatar.com/avatar/%{hash}?s=%{size}&d=identicon"
        # 通知email
        gitlab_rails['gitlab_email_from'] = '{{ .Values.email.gitlab_email_from }}'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = '{{ .Values.email.smtp_address }}'
        gitlab_rails['smtp_port'] = {{ .Values.email.smtp_port }}
        gitlab_rails['smtp_user_name'] = '{{ .Values.email.smtp_user_name }}'
        gitlab_rails['smtp_password'] = '{{ .Values.email.smtp_password }}'
        gitlab_rails['smtp_domain'] = '{{ .Values.email.smtp_domain }}'
        gitlab_rails['smtp_authentication'] = 'login'
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
        # Github登录
        gitlab_rails['omniauth_enabled'] = true
        gitlab_rails['omniauth_providers'] = [{
            "name" => "github",
            "app_id" => "{{ .Values.gitlab_rails.app_id }}",
            "app_secret" => "{{ .Values.gitlab_rails.app_secret }}",
            "args" => { "scope" => "user:email" }
        }]
        # 回复email
        gitlab_rails['incoming_email_enabled'] = true
        gitlab_rails['incoming_email_address'] = '{{ .Values.email.incoming_email_address }}'
        gitlab_rails['incoming_email_email'] = '{{ .Values.email.incoming_email_email }}'
        gitlab_rails['incoming_email_password'] = '{{ .Values.email.incoming_email_password }}'
        gitlab_rails['incoming_email_host'] = '{{ .Values.email.incoming_email_host }}'
        gitlab_rails['incoming_email_port'] = {{ .Values.email.incoming_email_port }}
        gitlab_rails['incoming_email_ssl'] = true
        gitlab_rails['incoming_email_start_tls'] = false
        gitlab_rails['incoming_email_mailbox_name'] = 'inbox'
        gitlab_rails['incoming_email_idle_timeout'] = 60
        # 反向代理下显示正确的真实IP
        nginx['real_ip_trusted_addresses'] = [ '192.168.1.0/24', '192.168.2.0/24', '2001:0db8::/32' ]
        nginx['real_ip_header'] = 'X-Forwarded-For'
        nginx['real_ip_recursive'] = 'on'
        # 关闭内置https
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        # 同时兼容http和https
        nginx['custom_gitlab_server_config'] = "set $$ssl 'on';\nif ($$http_x_forwarded_proto = 'http') {\n  set $$ssl 'off';\n}\nif ($$http_x_forwarded_proto = '') {\n  set $$ssl 'off';\n}"
        nginx['proxy_set_headers'] = {
            "Host" => "$$http_host",
            "X-Forwarded-Ssl" => "$$ssl"
        }