kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "gitlab.serviceAccountName" . }}
  labels:
  {{- include "gitlab.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ template "gitlab.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}