apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitlab.fullname" . }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gitlab.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitlab.fullname" . }}-ssh
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sshService.type }}
  ports:
    - port: {{ .Values.sshService.port }}
      targetPort: ssh
      protocol: TCP
      nodePort: {{ .Values.sshService.port }}
      name: ssh
  externalTrafficPolicy: Local
  selector:
    {{- include "gitlab.selectorLabels" . | nindent 4 }}
