apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "athens-proxy.fullname" . }}
  labels:
    {{- include "athens-proxy.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "athens-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "athens-proxy.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "athens-proxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ template "athens-proxy.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: ATHENS_DOWNLOAD_MODE
              value: {{ .Values.downloadMode }}
            - name: ATHENS_DISK_STORAGE_ROOT
              value: /var/lib/athens
            - name: ATHENS_STORAGE_TYPE
              value: disk
{{- if .Values.globalEndpoint }}
            - name: ATHENS_GLOBAL_ENDPOINT
              value: .Values.globalEndpoint
{{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/athens
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
