{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "athens-proxy.serviceAccountName" . }}
  labels:
{{ include "athens-proxy.labels" . | nindent 4 }}
{{- end -}}
