{{- if (.Values.deployment.imageCredentials).enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "application.imagepullname" $ }}
  namespace: {{ template "application.namespace" $ }}
  labels:
  {{- include "application.labels" $ | nindent 4 }}
{{- if .Values.deployment.imageCredentials.additionalLabels }}
{{ toYaml .Values.deployment.imageCredentials.additionalLabels | indent 4 }}
{{- end }}
{{- if .Values.deployment.imageCredentials.annotations }}
  annotations:
{{ toYaml .Values.deployment.imageCredentials.annotations | indent 4 }}
{{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "application.imagepullsecret" . }}
{{- end }}