kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "ingress-cert-reflector.fullname" . }}
  labels:
    {{- include "ingress-cert-reflector.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "watch", "get", "patch", "list"]
