kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "ingress-cert-reflector.fullname" . }}
  labels:
    {{- include "ingress-cert-reflector.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "ingress-cert-reflector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: {{ template "ingress-cert-reflector.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
