{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry-ui.fullname" . }}
data:
  # 生成账号的方法，一行一个账号
  # htpasswd -nb admin steven 
  users: |
  {{- if .Values.auth.users }}
    {{- join "\n" .Values.auth.users | b64enc | nindent 4 }}
  {{- else }}
    YWRtaW46JGFwcjEkVWE1R2J4b1IkSUhrcFpENmxBRlhKZHJ2M3JHeTdmMAoK
  {{- end }}
{{- end }}