{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "registry-ui.serviceAccountName" . }}
  labels:
{{ include "registry-ui.labels" . | nindent 4 }}
{{- end -}}
